// AUTO-GENERATED by scripts/affordability/scrape_budgetyourtrip.py
// Do not edit by hand.

export type DailyCostSeed = {
  foodUsd: number;
  transportUsd: number;
  activitiesUsd: number;
  hotelUsd: number;
  hostelUsd?: number;
};

export const DAILY_COSTS: Record<string, DailyCostSeed> = {
} as const;
